### ISSUE TITLE
ValueError: non-hexadecimal number found in fromhex()

### ISSUE THREAD

**Issue by robin571** [vanhoefm/fragattacks#26]
Hi all,
When I tried to check the tool in the AP mode testing, by below command

(venv) root@user-ThinkPad-T470p:/home/user/fragattacks/research# ./fragattack.py wlp3s0 --ap ping

Then let Wireless STA connect the AP with correct wpa passphrase, the testing will interrupt by below message

[14:03:37] This is FragAttack version 1.3.
[14:03:37] Detected iwlwifi, using injection bug workarounds
[14:03:37] Using interface monwlp3s0 (iwlwifi) to inject frames.
[14:03:37] Starting hostapd using: ../hostapd/hostapd -i wlp3s0 hostapd.conf -K
wlp3s0: interface state UNINITIALIZED->ENABLED
wlp3s0: AP-ENABLED 
wlp3s0: STA 54:2a:a2:17:a1:5e IEEE 802.11: authenticated
wlp3s0: AP-STA-ASSOCIATING 54:2a:a2:17:a1:5e handle_assoc
[14:03:47] Client 54:2a:a2:17:a1:5e is connecting
[14:03:47] Station: setting BSS MAC address ac:ed:5c:60:b2:88
wlp3s0: STA 54:2a:a2:17:a1:5e IEEE 802.11: associated (aid 1)
wlp3s0: EAPOL-TX 54:2a:a2:17:a1:5e 0203005f02008a001000000000000000019396bd5c3354fd70e33cfa1d1e498e4c870d4727f310112ac098d1b7e980e5f50000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[14:03:47] Action.StartAuth
[14:03:47] [Injected packet] <Dot11  subtype=8 type=Data FCfield=from-DS addr1=54:2a:a2:17:a1:5e addr2=ac:ed:5c:60:b2:88 addr3=ac:ed:5c:60:b2:88 SC=256 |<Dot11QoS  TID=1 |<LLC  dsap=0xaa ssap=0xaa ctrl...
wlp3s0: EAPOL-TX 54:2a:a2:17:a1:5e 020300970213ca001000000000000000029396bd5c3354fd70e33cfa1d1e498e4c870d4727f310112ac098d1b7e980e5f50000000000000000000000000000000000000000000000000000000000000000584d5269161755de5aaf7ed1d5c205940038dc0a40d923552186bda10a74b23a182887325d42f58cb0e5123f801f6f70d34bf897105291e23acdc434ebdbcc674c94df8953168d2fe73c
[14:03:47] Action.BeforeAuth
[14:03:47] [Injected packet] <Dot11  subtype=8 type=Data FCfield=from-DS addr1=54:2a:a2:17:a1:5e addr2=ac:ed:5c:60:b2:88 addr3=ac:ed:5c:60:b2:88 SC=272 |<Dot11QoS  TID=1 |<LLC  dsap=0xaa ssap=0xaa ctrl...
wlp3s0: AP-STA-CONNECTED 54:2a:a2:17:a1:5e
wlp3s0: STA 54:2a:a2:17:a1:5e RADIUS: starting accounting session 58776B4692D03962
wlp3s0: STA 54:2a:a2:17:a1:5e WPA: pairwise key handshake completed (RSN)
Traceback (most recent call last):
  File "./fragattack.py", line 271, in <module>
    daemon.run()
  File "/home/user/fragattacks/research/fraginternals.py", line 936, in run
    self.handle_wpaspy(msg)
  File "/home/user/fragattacks/research/fraginternals.py", line 1061, in handle_wpaspy
    self.stations[clientmac].handle_authenticated()
  File "/home/user/fragattacks/research/fraginternals.py", line 598, in handle_authenticated
    self.update_keys()
  File "/home/user/fragattacks/research/fraginternals.py", line 592, in update_keys
    self.tk = self.daemon.get_tk(self)
  File "/home/user/fragattacks/research/fraginternals.py", line 962, in get_tk
    return bytes.fromhex(tk)
ValueError: non-hexadecimal number found in fromhex() arg at position 32
[14:03:47] Closing daemon and cleaning up ...
wlp3s0: interface state ENABLED->DISABLED
wlp3s0: AP-STA-DISCONNECTED 54:2a:a2:17:a1:5e
wlp3s0: AP-DISABLED 
wlp3s0: CTRL-EVENT-TERMINATING 
nl80211: deinit ifname=wlp3s0 disabled_11b_rates=0

**Comment by vanhoefm** [comment]
If you solved this yourself, please post your solution as well.

This might have been caused by race conditions. If someone else gets their error, please re-open this issue.
