### ISSUE TITLE
[Errno 100] Network is down

### ISSUE THREAD

**Issue by jam821006** [vanhoefm/fragattacks#27]
When I try to use the command to ping my AP, I got the following result.

(venv) root@D630MT333:/home/cbn/fragattacks/research# ./fragattack.py wlx00c0caad8c11 --ap ping
[17:46:22] This is FragAttack version 1.3.
[17:46:22] Using interface monwlx00c0caad8 (mt76x2u) to inject frames.
[17:46:22] Starting hostapd using: ../hostapd/hostapd -i wlx00c0caad8c11 hostapd.conf -K
wlx00c0caad8c11: interface state UNINITIALIZED->ENABLED
wlx00c0caad8c11: AP-ENABLED 
wlx00c0caad8c11: STA 38:43:7d:ff:7e:71 IEEE 802.11: disassociated
wlx00c0caad8c11: INTERFACE-DISABLED 
Traceback (most recent call last):  
File "./fragattack.py", line 271, in <module>
    daemon.run()
File "/home/cbn/fragattacks/research/fraginternals.py", line 931, in run
    p = self.sock_eth.recv()
File "/home/cbn/fragattacks/research/venv/lib/python3.8/site-packages/scapy/supersocket.py", line 61, in recv
    cls, val, ts = self.recv_raw(x)
File "/home/cbn/fragattacks/research/venv/lib/python3.8/site-packages/scapy/arch/linux.py", line 551, in recv_raw
    pkt, sa_ll = self._recv_raw(self.ins, x)
File "/home/cbn/fragattacks/research/venv/lib/python3.8/site-packages/scapy/arch/linux.py", line 530, in _recv_raw
    pkt, ancdata, flags, sa_ll = sock.recvmsg(x, flags_len)
OSError: [Errno 100] Network is down[17:46:38] 
Closing daemon and cleaning up ...
wlx00c0caad8c11: interface state ENABLED->DISABLED
wlx00c0caad8c11: AP-DISABLED 
wlx00c0caad8c11: CTRL-EVENT-TERMINATING 
nl80211: deinit ifname=wlx00c0caad8c11 disabled_11b_rates=0

Didn't my Patched Driver install successfully?
I use alfa AWUS036ACM and Ubuntu 20.04

**Comment by vanhoefm** [comment]
If you solved this yourself, please post your solution as well.

My hunch here was that Wi-Fi was not disabled in the network manager and this was causing conflicts.

**Comment by jam821006** [comment]
Hi, vanhoefm,

Thank you for your response. This issue is my mistake to use commend to test AP.
Wanting to test AP, the commend is  
./fragattack.py wlx00c0caad8c11 ping 
and  client.conf must be modified.
Otherwise, the --debug 2 is very important. Thank your tool, let us test wifi security
