### ISSUE TITLE
L2Socket is Not defined | wifi.py | line 208

### ISSUE THREAD

**Issue by Ma5onic** [vanhoefm/fragattacks#31]
This issue has occurred in some of your other work but the suggestions to rename doesn't not solve the issue: 
#https://github.com/vanhoefm/krackattacks-scripts/issues/2#issuecomment-766244603

I installed the OS from your live image, using the "install ubuntu button"; scapy was missing & so was the "crypto" module (pycryptodome). Once those were installed, I encountered the `NameError: 'L2Socket' is Not defined issue`

I made sure to activate the virtual environment before every try.

**Comment by vanhoefm** [comment]
I haven't tested installing the OS from the live image. Just run the live image directly without installing.

Additionally, assure to first become root and then activate the virtual environment. Don't run the script using `sudo ./fragattacks.py` because the virtual environment _might_ then disappear on some Linux distributions.

**Comment by bollytom** [comment]
Hi,
I met the same issue when I ran the scripts, the output as below, but the suggestions to rename doesn't not solve the issue:

root@securitytest-Latitude-E5470:/home/securitytest/fragattacks/research# ./fragattack.py wlx00117f1ba967 
Traceback (most recent call last):
  File "./fragattack.py", line 9, in <module>
    from fraginternals import *
  File "/home/securitytest/fragattacks/research/fraginternals.py", line 7, in <module>
    from libwifi import *
  File "/home/securitytest/fragattacks/research/libwifi/__init__.py", line 1, in <module>
    from .wifi import *
  File "/home/securitytest/fragattacks/research/libwifi/wifi.py", line 217, in <module>
    class MonitorSocket(L2Socket):
NameError: name 'L2Socket' is not defined

Could you help me troubleshooting the issue please?

Thank you in advance!

Best Regards,

**Comment by vanhoefm** [comment]
Load the python virtual environment using `source venv/bin/activate` as explained in [before every usage](https://github.com/vanhoefm/fragattacks#5-before-every-usage).

**Comment by bollytom** [comment]
Many thanks vanhoefm for your quick reply!
I activated the virtual environment before the try just now and then retried it again, but still got the same result.

**Comment by bollytom** [comment]
Thank you for the guidance and help!
The L2Socket issue was fixed, now when I tried to test the scripts, we met the problem as below shown,

(venv) root@securitytest-Latitude-E5470:/home/securitytest/fragattacks/research# ./fragattack.py wlx00117f1ba967 ping 
[15:00:38] This is FragAttack version 1.3.
[15:00:38] You are not running patched drivers, meaning this tool may give incorrect results!
[15:00:38] To ignore this warning and timeout add the parameter --no-drivercheck
[15:00:43] Detected ath9k_htc, using injection bug workarounds
[15:00:43] WARNING: Unable to check if the ath9k_htc device is using patched firmware!
[15:00:43] Using interface monwlx00117f1ba (ath9k_htc) to inject frames.
[15:00:43] Starting wpa_supplicant using: ../wpa_supplicant/wpa_supplicant -Dnl80211 -i wlx00117f1ba967 -cclient.conf -W -K
Successfully initialized wpa_supplicant
wlx00117f1ba967: SME: Trying to authenticate with 04:f1:69:06:af:ab (SSID='testlab' freq=2452 MHz)
wlx00117f1ba967: CTRL-EVENT-DISCONNECTED bssid=04:f1:69:06:af:ab reason=2 locally_generated=1
wlx00117f1ba967: Trying to associate with 04:f1:69:06:af:ab (SSID='testlab' freq=2452 MHz)
wlx00117f1ba967: SME: Association request to the driver failed
BSSID 04:f1:69:06:af:ab blacklist count incremented to 2, blacklisting for 10 seconds
wlx00117f1ba967: SME: Trying to authenticate with 04:f1:69:06:af:ab (SSID='testlab' freq=2452 MHz)
wlx00117f1ba967: Trying to associate with 04:f1:69:06:af:ab (SSID='testlab' freq=2452 MHz)
wlx00117f1ba967: SME: Association request to the driver failed
wlx00117f1ba967: SME: Trying to authenticate with 04:f1:69:06:af:ab (SSID='testlab' freq=2452 MHz)
wlx00117f1ba967: Trying to associate with 04:f1:69:06:af:ab (SSID='testlab' freq=2452 MHz)
wlx00117f1ba967: SME: Association request to the driver failed
BSSID 04:f1:69:06:af:ab blacklist count incremented to 2, blacklisting for 10 seconds
wlx00117f1ba967: CTRL-EVENT-SSID-TEMP-DISABLED id=0 ssid="testlab" auth_failures=1 duration=10 reason=CONN_FAILED
wlx00117f1ba967: Associated with 04:f1:69:06:af:ab
wlx00117f1ba967: EAPOL-TX 04:f1:69:06:af:ab 0103007502010a0000000000000000000132e906aadc787987654e4329c4c558302e4b00f2476b914411b2c843fbe6802a0000000000000000000000000000000000000000000000000000000000000000d77d1f59084ddeed16118cd0f99932e0001630140100000fac040100000fac040100000fac020000
wlx00117f1ba967: CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
wlx00117f1ba967: WPA: Invalid EAPOL-Key MIC when using TPTK - ignoring TPTK
wlx00117f1ba967: WPA: Could not verify EAPOL-Key MIC - dropping packet
[15:00:55] Station: setting BSS MAC address 04:f1:69:06:af:ab
[15:00:55] Action.StartAuth
[15:00:55] [Injected packet] <Dot11  subtype=8 type=Data FCfield=to-DS addr1=04:f1:69:06:af:ab addr2=00:11:7f:1b:a9:67 addr3=04:f1:69:06:af:ab SC=256 |<Dot11QoS  TID=1 |<LLC  dsap=0xaa ssap=0xaa ctrl=3...
wlx00117f1ba967: CTRL-EVENT-SIGNAL-CHANGE above=1 signal=-41 noise=9999 txrate=58500
[15:01:01] The 4-way handshake has timed out for an unknown reason.
[15:01:01] Closing daemon and cleaning up ...
wlx00117f1ba967: CTRL-EVENT-DISCONNECTED bssid=04:f1:69:06:af:ab reason=3 locally_generated=1
wlx00117f1ba967: WPA: 4-Way Handshake failed - pre-shared key may be incorrect
wlx00117f1ba967: CTRL-EVENT-SSID-TEMP-DISABLED id=0 ssid="testlab" auth_failures=2 duration=25 reason=WRONG_KEY
nl80211: deinit ifname=wlx00117f1ba967 disabled_11b_rates=0
wlx00117f1ba967: CTRL-EVENT-TERMINATING 

And I have already modified the research/client.conf file before running the scripts.

I noticed that is shown 'SME: Association request to the driver failed', but I have already installed the drivers.

sudo apt-get install bison flex linux-headers-$(uname -r)
git clone https://github.com/vanhoefm/fragattacks-drivers58.git fragattacks-drivers58
cd fragattacks-drivers58
make defconfig-wifi
make -j 4
sudo make install

So how can I check if the patched driver is successfully installed or not?

Could you help me troubleshooting the issue please?

Thanks a lot!

Best Regards,

**Comment by vanhoefm** [comment]
> So how can I check if the patched driver is successfully installed or not?

The script will tell you, they're currently not properly installed. Restart your machine after installing them. After updating your kernel you must reinstall the modified drivers.

**Comment by vanhoefm** [comment]
Closing this since this seems to be resolved. You can still reply if you have related questions.

For those finding this by google: it's essential to use the python virtual environment, this assures a compatible version of Scapy is used. Newer versions of Scapy don't provide L2Socket by default and it requires a manual import.

**Comment by Ma5onic** [comment]
> Closing this since this seems to be resolved. You can still reply if you have related questions.
> 
> For those finding this by google: it's essential to use the python virtual environment, this assures a compatible version of Scapy is used. Newer versions of Scapy don't provide L2Socket by default and it requires a manual import.

Would you happen to know which version of Scapy Causes this break?

**Comment by vanhoefm** [comment]
Unfortunately, I don't know. You could try installing different Scapy versions in the virtual environment to find out. Or check the commit history at Scapy to see when this changed.
